export const GET_STORE_ID = 'GET_STORE_ID';
export const CHANGE_STORE = 'CHANGE_STORE';
export const STORE_LOCALE = 'STORE_LOCALE';
export const LOADING_SPINNER = 'LOADING_SPINNER';
export const LOADING_SPINNER_PRODUCT = 'LOADING_SPINNER_PRODUCT'

export const GET_MY_CART = 'GET_MY_CART';
export const CLEAR_CART_ITEM = 'CLEAR_CART_ITEM';
export const CHANGE_QTY = 'CHANGE_QTY';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const GET_SHIPPING_TYPE = 'GET_SHIPPING_TYPE';
export const SET_SHIPPING_TYPE = 'SET_SHIPPING_TYPE';
export const SET_ORDER_SUMMARY = 'SET_ORDER_SUMMARY';

export const GET_PAYMENT_CHECKOUT = 'GET_PAYMENT_CHECKOUT';
export const SET_PAYMENT_CHECKOUT = 'SET_PAYMENT_CHECKOUT';
export const GET_ORDER_DETAILS_CHECKOUT = 'GET_ORDER_DETAILS_CHECKOUT';
export const PLACE_ORDER_CHECKOUT = 'PLACE_ORDER_CHECKOUT';
export const UPDATE_NEW_QUOTE_ID = 'UPDATE_NEW_QUOTE_ID';

export const LOGIN = 'LOGIN';
export const INVALID_LOGIN = 'INVALID_LOGIN';
export const REGISTER = 'REGISTER';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CLEAR_CHANGE_PASS = 'CLEAR_CHANGE_PASS';
export const CLEAR_FORGOT_PASS = 'CLEAR_FORGOT_PASS';
export const CLEAR_REGISTRATION_ERROR = 'CLEAR_REGISTRATION_ERROR';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_ADDRESS_BOOK = 'GET_ADDRESS_BOOK';
export const ADD_NEW_ADDRESS = 'ADD_NEW_ADDRESS';
export const EDIT_ADDRESS = 'EDIT_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_STORE_LIST = 'GET_STORE_LIST';

export const GET_ORDER_HISTORY = 'GET_ORDER_HISTORY';
export const ORDER_DETAILS_VIEW = 'ORDER_DETAILS_VIEW';
export const CLEAR_STATE = 'CLEAR_STATE';

export const GET_WISHLIST_ITEM = 'GET_WISHLIST_ITEM';

export const ADD_PRODUCT_IN_WISHLIST = 'ADD_PRODUCT_IN_WISHLIST';
export const REMOVE_PRODUCT_FROM_WISHLIST = 'REMOVE_PRODUCT_FROM_WISHLIST';
export const GET_MENU_NAVIGATION = 'GET_MENU_NAVIGATION';
export const STORE_REGION = 'STORE_REGION';
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const GET_PRODUCT_COLOR = 'GET_PRODUCT_COLOR';
export const GET_PRODUCT_SIZE = 'GET_PRODUCT_SIZE';
export const GET_PRODUCT_BAND_SIZE = 'GET_PRODUCT_BAND_SIZE';
export const GET_PRODUCT_CUP_SIZE = 'GET_PRODUCT_CUP_SIZE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const GUEST_ADD_TO_CART = 'GUEST_ADD_TO_CART';

export const CREAR_PRODUCT_DETAILS = 'CREAR_PRODUCT_DETAILS';
export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const GET_PRODUCT_SEARCH_LIST = 'GET_PRODUCT_SEARCH_LIST';

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';

export const GUEST_USER_CART_ID = 'GUEST_USER_CART_ID';
export const GET_GUEST_USER_CART_ITEM = 'GET_GUEST_USER_CART_ITEM';
export const START_GUEST_CHECKOUT = 'START_GUEST_CHECKOUT';

export const GET_HOME_PAGE_DATA = 'GET_HOME_PAGE_DATA';

export const GET_FAQ_DATA = 'GET_FAQ_DATA';
export const GET_HELP_DATA = 'GET_HELP_DATA';

export const GET_PLACE_ORDER = 'GET_PLACE_ORDER';
export const VIP_REGISTER = 'VIP_REGISTER';

export const GET_IP_INFO = 'GET_IP_INFO';
export const REMOVE_OUT_OF_STOCK_ITEM = 'REMOVE_OUT_OF_STOCK_ITEM';

export const REDIRECT_TO_PAYMENT = 'REDIRECT_TO_PAYMENT';
export const REDIRECT_TO_DELIVERY = 'REDIRECT_TO_DELIVERY';
export const REDIRECT_TO_CART = 'REDIRECT_TO_CART';
export const GET_DISCOVER_CMS = 'GET_DISCOVER_CMS';

export const PRODUCT_DETAIL_LOADER = 'PRODUCT_DETAIL_LOADER';
export const PRODUCT_WISH_DETAIL = 'PRODUCT_WISH_DETAIL';

export const GET_CONTACT_US_DATA = 'GET_CONTACT_US_DATA';
export const SAVE_CONTACT_US_DATA = 'SAVE_CONTACT_US_DATA';
export const CLEAR_RESPONSE = 'CLEAR_RESPONSE';
export const SET_SIZE_CHART = 'SET_SIZE_CHART';
export const CARD_LOADER = 'CARD_LOADER';
export const ADD_TO_CARD_LOADER = 'ADD_TO_CARD_LOADER';
export const WISH_LIST_LOADER = 'WISH_LIST_LOADER';
export const QTY_UPDATE_LOADER = 'QTY_UPDATE_LOADER';

export const SET_ORDER_SUMMARY_DATA = 'SET_ORDER_SUMMARY_DATA';
export const SET_ORDER_DETAILS_LOADER = 'SET_ORDER_DETAILS_LOADER';
export const CLEAR_RESETPASSWORD_FLAG = 'CLEAR_RESETPASSWORD_FLAG';
export const RESETPASSWORD_LOADER = 'RESETPASSWORD_LOADER';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';